file(GLOB FRAMEWORK_TEST_SRCS "./*.cpp")
foreach(FRAMEWORK_TEST_SRC ${FRAMEWORK_TEST_SRCS})
  get_filename_component(TEST_NAME ${FRAMEWORK_TEST_SRC} NAME_WE)
  add_executable(${TEST_NAME} ${BASE_SRC} ${FRAMEWORK_TEST_SRC})
  target_include_directories(${TEST_NAME} PUBLIC ${LATCH_ROOT_DIR}/src)
  target_link_libraries(${TEST_NAME} latch_base_static)
  target_link_libraries(${TEST_NAME} gtest gtest_main)
  target_link_libraries(${TEST_NAME} spdlog)
  target_link_libraries(${TEST_NAME} pthread dl)
  target_link_libraries(${TEST_NAME} sqlite3)
  target_link_libraries(${TEST_NAME} ramulator)
  add_test(NAME ${TEST_NAME} COMMAND ${TEST_NAME})
endforeach()
